### ISSUE TITLE
AI doesn't turn to fire on you when garrisoned

### ISSUE THREAD

**Issue by astruyk** [astruyk/Ares#179]
From http://forums.bistudio.com/showthread.php?185254-Ares-Modules-expanding-Zeus-functionality-Release-Thread&p=2880536&viewfull=1#post2880536 

> When AI is garrisoning a building, and a player enters it, the AI is not able to turn around and attack him, I think the garrison script forces them to keep looking out of the window.

I feel like I fixed this once already...

**Comment by TheOtherTaylor** [comment]
From gm'ing I'm noticing that the AI that have been garrisoned will turn back to "face the window" they were originally tasked with facing even when I drag them to another location and try to make them look another way.

I think the issue is with the "lookAt" command on this line:
>131    (_units select _unitIndex) lookAt ([_housePos, CHECK_DISTANCE, (90 - _i), (_housePos select 2) - (getTerrainHeightASL _housePos)] call _Zen_ExtendPosition);

Possibly giving them a dowatch (https://community.bistudio.com/wiki/doWatch) at the position and then giving them a dowatch null (or however that should look in correct syntax) will cause them to initially turn to the position and then go back into freelook.

**Comment by astruyk** [comment]
Switching to doWatch instead of lookAt seems to have fixed it. If it was ever broken. I didn't fully test this out before the change. Afterwards I was able to place units, garrison them, move close and fire my weapon to alert them and they would turn and shoot me.

**Comment by TheOtherTaylor** [comment]
After you place them, can you turn them using zeus and have them stay facing the new direction?  One of the odd behaviors of lookAt was that even if you turned the unit manually it would always turn back to the original destination.
